name: ocds_redflags_engine

services:
  api:
    container_name: ocds_api
    build: .
    command: uv run uvicorn src.interfaces.api.main:app --host 0.0.0.0 --port ${PORT:-8000} --log-config log_config.yaml
    env_file: .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  worker:
    container_name: ocds_etl_worker
    build: .
    command: uv run python -m src.interfaces.worker
    env_file: .env
    restart: unless-stopped
