version: 1
disable_existing_loggers: False
formatters:
    standard:
        format: "%(levelname)-8s | %(name)s:%(lineno)d - %(message)s"
        # format: "%(asctime)s | %(levelname)-8s | %(name)s:%(lineno)d - %(message)s"
        # datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
    console:
        class: logging.StreamHandler
        formatter: standard
        stream: ext://sys.stdout
loggers:
    uvicorn:
        handlers: [console]
        propagate: no
    uvicorn.error:
        handlers: [console]
        propagate: no
    uvicorn.access:
        handlers: [console]
        propagate: no
    # logger de la app
    src:
        handlers: [console]
        propagate: no
    # logger asyncpg
    asyncpg:
        handlers: [console]
        level: DEBUG
        propagate: no
root:
    handlers: [console]
    level: INFO
